public with sharing class ConfirmationEmailController {
    public String participantID {get; set;}

    public String FirstName {get; set;}
    public String StartDateTime {get; set;}
    public String EndDateTime {get; set;}
    public String Street {get; set;}
    public String PLZ {get; set;}
    public String City {get; set;}
    public String Country {get; set;}
    public String CompanyName {get; set;}
    public String CompanyWebSite {get; set;}
    public String CompanyEmail {get; set;}
    public String CompanyPhone {get; set;}
    public String CompanyFax {get; set;}

    public ConfirmationEmailController() {

    }
}